'use strict';

module.exports = {
  'minBodyLength': 200, // 最小字数要求，同时也是概览长度

  'weeklyReminderName': 'github-blogs-weekly', // 发布周更新的repo名称
  'dailyReminderName': 'github-blogs-daily', // 发布日更新的repo名称
  'reminderIssuesLabel': 'Articles', // 发布更新Issue时添加的label

  // 开放性的repo，对该列表中的repo读取更新时会跳过"本人发布"的限制
  'orgRepos': [
    'amfe/article',
    'tmallfe/tmallfe.github.io',
    'baixing/FE-Blog',
    'gf-rd/blog'
  ],
  // Blog list
  'repos': [
    'fouber/blog',
    'amfe/article',
    'lifesinger/blog',
    'xufei/blog',
    'tmallfe/tmallfe.github.io',
    'cssmagic/blog',
    'kuitos/kuitos.github.io',
    'livoras/blog',
    'yisibl/blog',
    'wintercn/blog',
    'camsong/blog',
    'riskers/blog',
    'coderyi/blog',
    'lukego/blog',
    'hax/hax.github.com',
    'atian25/blog',
    'Lucifier129/Lucifier129.github.io',
    'bh-lay/blog',
    'dfguo/blog',
    'cnsnake11/blog',
    'onface/blog',
    'chyingp/blog',
    'ant-ued/blog',
    'viktorklang/blog',
    'msurguy/blog',
    'SimplyY/blog',
    'matthew-sun/blog',
    'BayesianLogic/blog',
    'niklasfrykholm/blog',
    'enml/blog',
    'tikonen/blog',
    'lcxfs1991/blog',
    'classicemi/blog',
    'rccoder/blog',
    'baixing/FE-Blog',
    'web2hack/blog',
    'bgolub/blog',
    'ruhoh/blog',
    'ccjr/blog',
    'p2227/p2227.github.io',
    'hxoht/blog',
    'jakubholynet/blog',
    'huangz1990/blog',
    'pixelhandler/blog',
    'ma6174/blog',
    'LearnShare/blog',
    '28harishkumar/blog',
    'steveklabnik/blog',
    'ashfurrow/blog',
    'zhiqiang21/blog',
    'wenzhixin/blog',
    'hueitan/blog',
    'mafintosh/blog',
    'ipfs/blog',
    'ljw1004/blog',
    'imsobear/blog',
    'fwon/blog',
    'mominger/blog',
    'zhaoda/blog',
    'zhouwenbin/blog',
    'Gaubee/blog',
    'YIXUNFE/blog',
    'thoughtram/blog',
    'GitbookIO/blog',
    'zwhu/blog',
    'alvarto/blog',
    'xieranmaya/blog',
    'ngot/blog',
    'fxhover/blog',
    'techird/blog',
    'siddontang/blog',
    'serverfireteam/blog',
    'fperez/blog',
    'aui/blog',
    'nathanleclaire/blog',
    'pivotal-legacy/blog',
    'linxz/blog',
    'confidence68/blog',
    'creeperyang/blog',
    'substack/blog',
    'luqin/blog',
    'woto/blog',
    'kerryChen95/blog',
    'sorrycc/blog',
    'josef-jelinek/blog',
    'fredshare/blog',
    'Hiufan/blog',
    'Pearyman/blog',
    'chunpu/blog',
    'qq610540622/blog',
    'arogulin/blog',
    'pimcore-extensions/blog',
    'divarvel/blog',
    'yutingzhao1991/blog',
    'nareix/blog',
    'strikingly/blog',
    'yikebocai/blog',
    'jollen/blog',
    'yegor256/blog',
    'tarekziade/blog',
    'ecomfe/blog',
    'LingyuCoder/blog',
    'madewithlove/blog',
    'lapwinglabs/blog',
    'coneo/blog',
    'lmk123/blog',
    'iocanel/blog',
    'kengonakajima/blog',
    'amilna/blog',
    'fightteam/blog',
    'mishe/blog',
    'bholst/blog',
    'Enome/blog',
    'youngwind/blog',
    'weexteam/article'
  ]
}
